### ISSUE TITLE
dbShowCollections not working with remote server

### ISSUE THREAD

**Issue by vrajs5** [tc/RMongo#31]
Hi

I am trying to fetch collection names from Mongo server using dbShowCollections, which is working for local mongodb server. But when I am trying to fetch it for remote one, dbShowCollections is returning blank string. Other queries are working well. 

Required package information
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
other attached packages:
[1] RMongo_0.0.25 rJava_0.9-6
```

Also at both end I am using MongoDB 3.0 with wiredTiger engine and zlib compression.

I checked with Python - pymongo, I am getting collection names there for remote as well as local server.

**Comment by stennie** [comment]
@vrajs5 For full WiredTiger / MongoDB 3.0 compatibility you need to be using the 2.13 or newer version of the Java driver (see: [MongoDB Version Compatibility](http://docs.mongodb.org/ecosystem/drivers/java/#mongodb-compatibility)). RMongo currently specifies [2.12.2](https://github.com/tc/RMongo/blob/master/src/r-mongo-scala/pom.xml#L53) as a dependency.

Upgrading the Java driver should resolve your issue listing collections in WiredTiger.

**Comment by tc** [comment]
Thanks @stennie I just updated the package to specify 2.13.0 which should support MongoDB 3.0.

@vrajs5 you can build the package from the master branch and install it directly or wait until CRAN approves the package. It will be RMongo version 0.1.0.

**Comment by theroys** [comment]
What is the timeframe for approval by CRAN

**Comment by tc** [comment]
@theroys we need someone to volunteer to re-submit it to CRAN. They rejected it due to some directory structure changes last time which i think of the pull requests fixed.

**Comment by stennie** [comment]
@tc I can volunteer, but doesn't the CRAN submission have to come from an approved maintainer email?

**Comment by tc** [comment]
CRAN has a web submission form now.
