### ISSUE TITLE
Issue with dbGetQuerry

### ISSUE THREAD

**Issue by SwatiGMittal** [tc/RMongo#44]
When I write dbGetQuery to get all the document of a collection, the number of data objects created in R is more than the number of document in the MongoDB collection.

**Comment by tc** [comment]
@SwatiGMittal how many documents are in the collection?

If you create a new collection with 20 and another new collection with 1000 and run the dbGetQuery, what are the number of data objects returned?

**Comment by SwatiGMittal** [comment]
@tc I have around 6 collections each with more than 200 documents .  I am working with twitter data where I am collecting tweets based on certain keywords. So, if I create a new test collection with 20 and 1000 and run dbGetQuery I get 20 and 1000 objects respectively. But when I run the same query on my collections number of R objects almost doubles.

**Comment by tc** [comment]
can you include a test case we can copy and paste into R to debug?
