### ISSUE TITLE
Get JSON documents

### ISSUE THREAD

**Issue by zappingseb** [tc/RMongo#51]
Hi,

thank you for the great package. Would it be possible to derive the DBCursor just as a JSON by JSON.serialize() instead of CSV or simple strings?

This would be really useful as we upload documents with linebreaks (\n) to our DB

How can I compile your code? Can you provide the build.sbt ?

**Comment by tc** [comment]
Hi,
you can re-compile the scala package in the https://github.com/tc/RMongo/tree/master/src/r-mongo-scala folder

I was using maven as the build system as opposed to sbt.

``maven build`` should work.
